// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://lsdgnsmzvfsadctttadk.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxzZGduc216dmZzYWRjdHR0YWRrIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY3MjUwNjcsImV4cCI6MjA3MjMwMTA2N30.gHQAdsCXltKCFmDHSKIXHHhdaJe25vBI369AALFmokc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});